#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Project4Bicycle.Droid.Resource", IsApplication=true)]

namespace Project4Bicycle.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Project4Bicycle.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Project4Bicycle.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::Project4Bicycle.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fadein = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fadeout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int scale_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int scale_out = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AppIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int SplashImageLand = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int SplashImagePort = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int SplashScreenLand = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int SplashScreenPort = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int verkeersbord = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int axisLayout = 2131165192;
			
			// aapt resource value: 0x7f070010
			public const int bottom_labels = 2131165200;
			
			// aapt resource value: 0x7f070002
			public const int chartAreaLayout = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int chartTitle = 2131165185;
			
			// aapt resource value: 0x7f070011
			public const int content = 2131165201;
			
			// aapt resource value: 0x7f070006
			public const int dataMarkerLayout = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int gridLineLayout = 2131165187;
			
			// aapt resource value: 0x7f070012
			public const int gridLinesLayout = 2131165202;
			
			// aapt resource value: 0x7f07000d
			public const int iconView = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int label = 2131165198;
			
			// aapt resource value: 0x7f07000a
			public const int legendHeader = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int legendItemsLayout = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int legendScrollView = 2131165195;
			
			// aapt resource value: 0x7f070009
			public const int legendViewGroup = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int rootLayout = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int seriesLayout = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int stripLinesLayout = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int technicalIndicatorLayout = 2131165191;
			
			// aapt resource value: 0x7f070013
			public const int thumbLayout = 2131165203;
			
			// aapt resource value: 0x7f07000f
			public const int top_labels = 2131165199;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int chart_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int chart_legend = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int chart_legend_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int range_navigator_layout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int ApplicationName = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int Hello = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int q = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int quarter = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int w = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int week = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
